version: '3'

services:
    website:
        container_name: docker_django
        build: 
            context: ./srcs/website
        command: python manage.py runserver 0.0.0.0:8000
        environment:
            POSTGRES_DB: docker
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
        env_file:
            - .env
        ports:
            - 8000:8000
        networks:
            - transcendence
        depends_on:
            - postgres
        restart: always

    postgres:
        container_name: docker_postgres
        build:
            context: ./srcs/database
        environment:
            POSTGRES_DB: docker
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
        env_file:
            - .env
        volumes:
            - postgres:/var/lib/postgresql/data
        networks:
            - transcendence
        restart: always

networks:
    transcendence:
        name: transcendence
        driver: bridge

volumes:
    postgres:
        name: postgres
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ../data/postgres