version: '3'

services:
    nginx:
        container_name: nginx
        build:
            context: ./srcs/nginx
        image: nginx
        networks:
            - transcendence
        ports:
            - 3000:80
        volumes:
            - shared_data:/var/www/static/
        depends_on:
            - website
        restart: always

    website:
        container_name: django
        build:
            context: ./srcs
        environment:
            IP_LOCAL: ${IP_LOCAL}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            INTRA_USER: ${INTRA_USER}
            INTRA_SECRET: ${INTRA_SECRET}
        env_file:
            - .env
        # ports:
        #     - 3000:3000
        volumes:
            - shared_data:/var/www/static/
        networks:
            - transcendence
        depends_on:
            postgres:
                condition: service_healthy
        restart: always

    postgres:
        container_name: postgres
        image: postgres:16-bullseye
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes: 
          - postgres_volume:/var/lib/postgresql/data
        networks:
          - transcendence
        healthcheck:
            test: ["CMD", "pg_isready"]
            interval: 10s
            timeout: 15s
            retries: 12

networks:
    transcendence:
        name: transcendence
        driver: bridge

volumes:
    postgres_volume:
        name: postgres_volume
        driver: local

    shared_data:
        name: shared_data
