version: '3'

services:
    nginx:
        container_name: nginx
        build:
            context: ./srcs/nginx
        image: nginx
        networks:
            - transcendence
        ports:
            - 3000:80
        volumes:
            - shared_data:/var/www/static/
        depends_on:
            - website
        restart: always

    website:
        container_name: django
        build:
            context: ./srcs
        env_file:
            - .env
        volumes:
            - shared_data:/var/www/static/
            - images:/app/server/avatar
        networks:
            - transcendence
        depends_on:
            postgres:
                condition: service_healthy
        restart: always

    postgres:
        container_name: postgres
        image: postgres:16-bullseye
        restart: always
        env_file:
            - .env
        volumes: 
          - postgres_volume:/var/lib/postgresql/data
        networks:
          - transcendence
        healthcheck:
            test: ["CMD", "pg_isready"]
            interval: 10s
            timeout: 15s
            retries: 12

networks:
    transcendence:
        name: transcendence
        driver: bridge

volumes:
    postgres_volume:
        name: postgres_volume
        driver: local

    images:
        name: images
        driver: local

    shared_data:
        name: shared_data
