version: '3'

services:
    website:
        container_name: docker_django
        build: 
            context: ./srcs
        environment:
            # POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        env_file:
            - .env
        ports:
            - 8000:8000
        networks:
            - transcendence
        depends_on:
            postgres:
                condition: service_healthy
        restart: always

    postgres:
        container_name: docker_postgres
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            # POSTGRES_DB: ${POSTGRES_DB}
        volumes: 
          - postgres_volume:/var/lib/postgresql/data
        networks:
          - transcendence
        healthcheck:
            test: ["CMD", "pg_isready"]
            interval: 10s
            timeout: 15s
            retries: 12

networks:
    transcendence:
        name: transcendence
        driver: bridge

volumes:
    postgres_volume:
        name: postgres_volume
        driver: local
        # driver_opts:
        #     type: none
        #     o: bind
        #     device: ./data/postgres