version: '3'

services:
    website:
        container_name: docker_django
        build: 
            context: ./srcs/website
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        env_file:
            - .env
        ports:
            - 8000:8000
        networks:
            - transcendence
        depends_on:
            - postgres
        restart: always

    postgres:
        container_name: docker_postgres
        build:
            context: ./srcs/database
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        env_file:
            - .env
        volumes:
            - postgres_volume:/var/lib/postgresql/data
        networks:
            - transcendence
        restart: always

networks:
    transcendence:
        name: transcendence
        driver: bridge

volumes:
    postgres_volume:
        name: postgres_volume
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./data/postgres