version: '3'

services:
    web:
        build: 
            context: ./django
        container_name: docker_django
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        restart: always
