name: Docker Image CI for GHCR

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  OWNER: maxenceee
  IMAGE_NAME: ft_transcendence

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:
    - name: Deploy the new image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ${{ secrets.WORKDIR }}
          git pull
          make re


